app.name : spring-boot-config
my:
  greeting : Hello World!
  appGreeting : Welcome to ${app.name}

values : One,Two,Three
dbvalues : "{connectionString : 'http:/____',username : 'foo' , password : 'pass'}"

db :
   connection : connection-string-here
   host : 129.0.0.1
   port : 3306

spring.profiles.active : test